services:
  neo4j:
    platform: linux/amd64
    image: neo4j:5.26.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./docker/neo4j-data:/data
      - ./docker/neo4j-import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
